config/routes.rb
Rails.application.routes.draw do
 
  get '/' => 'homes#top'

  resources :lists
  
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end
  
  def create
    @list =List.new(list_params)
    if @list.save
      flash[:notice] = "Book was successfully created"
      redirect_to list_path(@list.id)
    else
      @lists = List.all
      render :index
    end
  end  

  def index
    @lists = List.all
    @list =List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
    
  end 
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
     
      flash[:notice] = "Book was successfully created"
      redirect_to list_path(@list.id)
    else
      render :edit
    end
  end
  
  def destroy
    list = List.find(params[:id])
    if list.destroy
     flash[:notice] = "Book was successfully destroyed."
     redirect_to '/lists'
    else
      render :show
    end  
    
  end
  
  
  private
  def list_params
    params.require(:list).permit(:title, :body)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>

<div class="top-text">Bookersでは、様々な書籍に関するあなたの意見や</div>
<div class="top-text">印象を共有することができます</div>

<span><%= link_to "Strat", '/lists' %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Editing Book</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list, url:list_path(@list.id), method: :patch do |f| %>

<div class="edit-field">Tilte
<p><%= f.text_field :title %></p>
</div>

<div class ="edit-field">Body
<p><%= f.text_area :body %></p>
</div>
<div class ="edit-field">
<%= f.submit 'Update Book' %>
</div>
<p></p>

<span><%= link_to "Show", list_path(@list.id) %></span>
|<span><%= link_to "Back", '/lists' %></span>




<% end %>

app/views/lists/index.html.erb
<div class="flash"><%= notice %></div>
<h1>Books</h1>

<table>
    <thead>
    <tr>
    <th>title</th> <th>body</th> <th colspan="3"></th></th>
    </tr>
    </thead>
    <tbody>
<% @lists.each do |list| %>
    <tr>
    <td width=30%><%= list.title %></td>
    <td width=50%><%= list.body %></td>
    <td><%= link_to "show", list_path(list.id) %></td>
    <td><%= link_to "edit", edit_list_path(list.id) %></td>
    <td><%= link_to "destroy", list_path(list.id), method: :delete, "data-confirm"=>"Are you sure?" %></td>
    </tr>

<% end %>
</tbody>
</table>

<h2>New book</h2>

<% if @list.errors.any? %>
<div class="error">
<div class="error-title">
  <%= @list.errors.count %>errors prohibited this book from being saved:
</div>
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %></div>

<%= form_with model: @list,yrl:'/lists', method: :post do |f| %>
 <div class="field">Title
 <p><%= f.text_field :title %></p>
 </div>
 <div class="field">Body
 <p><%= f.text_area :body %></P>
 </div>
 <div class="action">
 <%= f.submit 'Create Book' %>
 </div>
<% end %>

app/views/lists/new.html.erb
<h1>New book</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list,yrl:'/lists', method: :post do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>
 
 <h4>Body</h4>
 <%= f.text_area :body %>
 
 <%= f.submit 'Create Book' %>
<% end %>

app/views/lists/show.html.erb
<div class="flash"><%= notice %></div>


<div class="show-field">Title:
<%= @list.title %></div>

<div class="show-field">Body:
<%= @list.body %></div>



<span><%= link_to "Edit", edit_list_path(@list.id) %></span>
|
<span><%= link_to "Back", '/lists' %></span>